// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzizfplvrpnzuucurwlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aXpmcGx2cnBuenV1Y3Vyd2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTQ5MzYsImV4cCI6MjA2Mjg3MDkzNn0.ugAfj-3G7G_4LljPwJc7eTlQ9x3I82WalbpAFbzVOeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);